# docker-compose for Stack of Swag + Heimdall + HomeAssistant
# need to modify the swag configs in /data/docker/swag/config/nginx/proxy-confs/ to match

x-extra_hosts:
  # This is added so that within each service you can communicate to another service by using the DNS name of the host rather
  # than using IP address. Makes it easy if the IP address changes. For example, when configuring Radarr, you can
  # configure the transmission client url as http://docker_host_ip:9091
  &docker_host_ip
  # Pulls the IP address of the host from the .env file
  - "docker_host_ip:${HOST_IP}"

services:
  # Reverse proxy for all services hosted on the RPI
  # services are exposed via the domain name sent through the URL, configured via the conf files in nginx 
  swag:
    image: linuxserver/swag:latest    # https://docs.linuxserver.io/general/swag/#docker-compose
    container_name: swag
    hostname: swag
    extra_hosts: *docker_host_ip
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    networks:
      - homelab_net
      - media_net
    ports:
      # 80:80  # only needed if using http validation. We're using duckdns to validate, so don't need this
      - 443:443
    secrets:
      - DUCKDNSTOKEN
    environment:
      # Choose one of the following methods to set environment variables
      # 1. Set variables directly in the compose file
      PUID: 1003
      PGID: 1003
      TZ: ${TZ:-Australia/Melbourne}
      URL: ${SWAG_URL:?Please configure SWAG_URL in .env file}

      # 2. Set variables via substitution from .env file
      # PUID: ${SWAG_PUID} # TODO: not resepecting the .env file, using direct values for now
      # PGID: ${SWAG_PGID} # TODO: not resepecting the .env file, using direct values for now
      # URL: ${SWAG_URL:?Please configure SWAG_URL in .env file} # TODO: not resepecting the .env file, using direct values for now

      SUBDOMAINS: wildcard
      VALIDATION: duckdns
      FILE__DUCKDNSTOKEN: /run/secrets/DUCKDNSTOKEN
      #CERTPROVIDER: zerossl  # defaults to letsencrypt
      #EMAIL:   # required when using zerossl as cert provider
    volumes:
      - ${ROOT_CONFIG}/swag:/config

  # Do all of the home automation stuff here
  homeassistant:
    image: linuxserver/homeassistant:latest
    container_name: homeassistant
    hostname: homeassistant
    extra_hosts: *docker_host_ip   # this might work to allow the nginx config for homeassistant to reference the host IP by name
    network_mode: host  # home assistant needs network_mode: host for auto discovery and bluetooth
    restart: unless-stopped
    environment:
      # Choose one of the following methods to set environment variables
      # 1. Set variables directly in the compose file
      PUID: 1006
      PGID: 1006
      TZ: ${TZ:-Australia/Melbourne}

      # 2. Set variables via substitution from .env file
      # PUID: ${HOMEASSISTANT_PUID} # TODO: not resepecting the .env file, using direct values for now
      # PGID: ${HOMEASSISTANT_PGID} # TODO: not resepecting the .env file, using direct values for now

    volumes:
      - ${ROOT_CONFIG}/homeassistant/config:/config
      - /run/dbus:/run/dbus:ro
    # ports not needed, as this containers is exposed on the host network stack via network_mode: host
  
  homarr:
    image: ghcr.io/ajnart/homarr:latest
    container_name: homarr
    hostname: homarr
    extra_hosts: *docker_host_ip
    restart: unless-stopped
    networks:
      - homelab_net
      - media_net
    # no need to expose ports via docker, as the container is accessed via Swag. Left for posterity
    #ports:
    #  - 7575:7575
    environment:
      DISABLE_ANALYTICS: TRUE
      # Choose one of the following methods to set environment variables
      # 1. Set variables directly in the compose file
      PUID: 1019
      PGID: 1019
      TZ: ${TZ:-Australia/Melbourne}

      # 2. Set variables via substitution from .env file
      # PUID: ${HOMARR_PUID} # TODO: not resepecting the .env file, using direct values for now
      # PGID: ${HOMARR_PGID} # TODO: not resepecting the .env file, using direct values for now
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Optional, only if you want docker integration
      - ${ROOT_CONFIG}/homarr/configs:/app/data/configs
      - ${ROOT_CONFIG}/homarr/icons:/app/public/icons
      - ${ROOT_CONFIG}/homarr/data:/data

  # Bridge to allow Wyze cameras to be used in HomeAssistant via RTSP. https://github.com/mrlt8/docker-wyze-bridge
  wyze-bridge:
    image: mrlt8/wyze-bridge:latest
    #image: wyze-bridge-secret-edits   # TODO: switch back to release build once the changes that support secrets
                                      # make it into he mainline build
    container_name: wyze-bridge
    hostname: wyze-bridge
    extra_hosts: *docker_host_ip
    restart: unless-stopped
    networks:
      - homelab_net
    ports:
      # TODO: harden ports
      - 1935:1935 # RTMP - worst. probably don't want this
      - 8554:8554 # RTSP - next best. 
      - 8888:8888 # HLS - 2nd best.
      - 8889:8889 # WebRTC - best. 
      - 8189:8189/udp # WebRTC/ICE
      - 5000:5000 # WEB-UI
    secrets:
      # Due to the way that the fix for having secrets referenced via files was implemented (see
      # https://github.com/mrlt8/docker-wyze-bridge/issues/1244), if these these secrets exist the are read directly.
      # no need to set them in the environment variables
      - WYZE_EMAIL
      - WYZE_PASSWORD
      - API_ID
      - API_KEY
      - WB_USERNAME
      - WB_PASSWORD
    environment:
      # Choose one of the following methods to set environment variables
      # 1. Set variables directly in the compose file
      PUID: 1018
      PGID: 1018
      TZ: ${TZ:-Australia/Melbourne}

      # 2. Set variables via substitution from .env file
      # PUID: ${WYZEBRIDGE_PUID} # TODO: not resepecting the .env file, using direct values for now
      # PGID: ${WYZEBRIDGE_PUID} # TODO: not resepecting the .env file, using direct values for now


      # [OPTIONAL] Credentials can be set in the WebUI, but every time the container is restarted, the credentials will need to be re-entered.
      # instead, they are now all set via secrets and read from /run/secrets as per https://github.com/mrlt8/docker-wyze-bridge/issues/1244

      # API Key and ID can be obtained from the wyze dev portal: 
      # https://developer-api-console.wyze.com/#/apikey/view

      # [OPTIONAL] IP Address of the host to enable WebRTC e.g.,:
      WB_IP: docker_host_ip


# want to define a network range so that we can explicitly trust that network in the homeassistant config    
networks:
  homelab_net:
    name: homelab_net   # ensure network isn't prefixed with the default name of the directory, eg git_home_services_stack_homelab_net
    attachable: true
    ipam:
      config:
        - subnet: 172.100.0.0/24
  media_net:
    # Note: if the media stack has not been started, manually define the media_net network with
    # docker network create --attachable --subnet=172.200.0.0/24 media_net
    external: true

secrets:
  DUCKDNSTOKEN:
    file: ${SECRETS}/swag/duckdns_token
  WYZE_EMAIL:
    file: ${SECRETS}/wyzebridge/wyze_account_email
  WYZE_PASSWORD:
    file: ${SECRETS}/wyzebridge/wyze_account_password
  wyze_account_totp:
    file: ${SECRETS}/wyzebridge/wyze_account_totp
  API_ID:
    file: ${SECRETS}/wyzebridge/wyze_api_id
  API_KEY:
    file: ${SECRETS}/wyzebridge/wyze_api_key
  WB_USERNAME:
    file: ${SECRETS}/wyzebridge/wyze_bridge_webapp_username
  WB_PASSWORD:
    file: ${SECRETS}/wyzebridge/wyze_bridge_webapp_password
  MYSQL_ROOT_PASSWORD:
    file: ${SECRETS}/vikunja/mysql_root_password
  MYSQL_USER:
    file: ${SECRETS}/vikunja/mysql_user
  MYSQL_PASSWORD:
    file: ${SECRETS}/vikunja/mysql_password
