x-extra_hosts:
  # This is added so that within each service you can communicate to another service by using the DNS name of the host rather
  # than using IP address. Makes it easy if the IP address changes. For example, when configuring Radarr, you can
  # configure the transmission client url as http://aard:9091
  &aard
  # Pulls the IP address of the host from the .env file
  - "aard:${HOST_IP}"

services:
  wg-easy:
    image: ghcr.io/wg-easy/wg-easy
    #image: ghcr.io/wg-easy/wg-easy:nightly    # PASSWORD_HASH var only works with nightly build at the moment
    container_name: wg-easy
    hostname: wg-easy
    extra_hosts: *aard
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    #networks:
    ports:
      - "51820:51820/udp" # for tunnel connection
      - "51821:51821/tcp" # for webui
    secrets:
       - wireguard_password_hash
    environment:
      PUID: ${WIREGUARD_PUID}
      PGID: ${WIREGUARD_PGID}
      TZ: ${TZ:-Australia/Melbourne}

      # WebUI stuff
      PORT: ${WEBUI_PORT}
      #PASSWORD_HASH: /run/secrets/wireguard_password_hash    # secrets not yet built into wg-easy (Aug 2024)
      PASSWORD_HASH: ${WIREGUARD_PASSWORD_HASH:?Please configure WIREGUARD_PASSWORD_HASH in .env file}
      UI_TRAFFIC_STATS: true
      UI_CHART_TYPE: 3  # 1 = line, 2 = area, 3 = bar

      # VPN stuff
      WG_HOST: ${WIREGUARD_URL}
      WG_PORT: ${WIREGUARD_VPN_PORT}
      WG_PERSISTENT_KEEPALIVE: 25
      WG_ALLOWED_IPS: ${CLIENT_IP_RANGE}
      WG_DEFAULT_DNS: ${WIREGUARD_VPN_DNS}
      WG_DEFAULT_ADDRESS: 192.168.255.x      
      
      # WG_CONFIG_PORT: 92820    
      # WG_MTU: 1420
      # WG_ALLOWED_IPS: 192.168.15.0/24, 10.0.1.0/24
      # WG_PRE_UP: echo "Pre Up" > /etc/wireguard/pre-up.txt
      # WG_POST_UP: echo "Post Up" > /etc/wireguard/post-up.txt
      # WG_PRE_DOWN: echo "Pre Down" > /etc/wireguard/pre-down.txt
      # WG_POST_DOWN: echo "Post Down" > /etc/wireguard/post-down.txt


    volumes:
      - ${ROOT_CONFIG}/wireguard:/etc/wireguard
      - /lib/modules:/lib/modules:ro
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1

secrets:
  wireguard_password_hash:
    file: ${SECRETS}/wireguard/wireguard_password_hash


# volumes:
#   etc_wireguard:

# services:
#   wg-easy:
#     environment:
#       # Change Language:
#       # (Supports: en, ua, ru, tr, no, pl, fr, de, ca, es, ko, vi, nl, is, pt, chs, cht, it, th, hi)
#       - LANG=de
#       # ⚠️ Required:
#       # Change this to your host's public address
#       - WG_HOST=raspberrypi.local

      # Optional:
      # PASSWORD: foobar123 (deprecated, see readme)
      # PASSWORD_HASH: $$2y$$10$$hBCoykrB95WSzuV4fafBzOHWKu9sbyVa34GJr8VV5R/pIelfEMYyG (needs double $$, hash of 'foobar123'; see "How_to_generate_an_bcrypt_hash.md" for generate the hash)
      # PORT: 51821
      # WG_PORT: 51820
      # WG_CONFIG_PORT: 92820
      # WG_DEFAULT_ADDRESS: 10.8.0.x
      # WG_DEFAULT_DNS: 1.1.1.1
      # WG_MTU: 1420
      # WG_ALLOWED_IPS: 192.168.15.0/24, 10.0.1.0/24
      # WG_PERSISTENT_KEEPALIVE: 25
      # WG_PRE_UP: echo "Pre Up" > /etc/wireguard/pre-up.txt
      # WG_POST_UP: echo "Post Up" > /etc/wireguard/post-up.txt
      # WG_PRE_DOWN: echo "Pre Down" > /etc/wireguard/pre-down.txt
      # WG_POST_DOWN: echo "Post Down" > /etc/wireguard/post-down.txt
      # UI_TRAFFIC_STATS: true
      # UI_CHART_TYPE: 0 # (0 Charts disabled, 1 # Line chart, 2 # Area chart, 3 # Bar chart)

    # image: ghcr.io/wg-easy/wg-easy
    # container_name: wg-easy
    # volumes:
    #   - etc_wireguard:/etc/wireguard
    # ports:
    #   - "51820:51820/udp"
    #   - "51821:51821/tcp"
    # restart: unless-stopped
    # cap_add:
    #   - NET_ADMIN
    #   - SYS_MODULE
    #   # - NET_RAW # ⚠️ Uncomment if using Podman 
    # sysctls:
    #   - net.ipv4.ip_forward=1
    #   - net.ipv4.conf.all.src_valid_mark=1