x-extra_hosts:
  # This is added so that within each service you can communicate to another service by using the DNS name of the host rather
  # than using IP address. Makes it easy if the IP address changes. For example, when configuring Radarr, you can
  # configure the transmission client url as http://aard:9091
  &aard
  # Pulls the IP address of the host from the .env file
  - "aard:${HOST_IP}"

services:
  wg-easy:
    #image: ghcr.io/wg-easy/wg-easy
    image: ghcr.io/wg-easy/wg-easy:nightly    # PASSWORD_HASH var only works with nightly build at the moment
    container_name: wg-easy
    hostname: wg-easy
    extra_hosts: *aard
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    #networks:
    ports:
      - "51820:51820/udp" # for tunnel connection
      - "51821:51821/tcp" # for webui
    # secrets:    # see secrets section below
    #    - wireguard_password_hash
    environment:
      PUID: ${WIREGUARD_PUID}
      PGID: ${WIREGUARD_PGID}
      TZ: ${TZ:-Australia/Melbourne}

      # WebUI stuff
      PORT: ${WEBUI_PORT}
      #PASSWORD_HASH: /run/secrets/wireguard_password_hash    # see secrets section below
      PASSWORD_HASH: ${WIREGUARD_PASSWORD_HASH:?Please configure WIREGUARD_PASSWORD_HASH in .env file}
      UI_TRAFFIC_STATS: true
      UI_CHART_TYPE: 3  # 1 = line, 2 = area, 3 = bar

      # VPN stuff
      WG_HOST: ${WIREGUARD_URL}
      WG_PORT: ${WIREGUARD_VPN_PORT}
      WG_PERSISTENT_KEEPALIVE: 25
      WG_ALLOWED_IPS: ${IP_RANGES_TO_ROUTE_THROUGH_WG}
      WG_DEFAULT_DNS: ${WIREGUARD_VPN_DNS}
      WG_DEFAULT_ADDRESS: ${IP_RANGE_FOR_WG_CLIENTS}

    volumes:
      - ${ROOT_CONFIG}/wireguard:/etc/wireguard
      - /lib/modules:/lib/modules:ro
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    
    labels:
      # this should flag watchtower to only monitor this container, not apply updates
      # as this openvpn image is a local image, there's never going to be a upstream update
      # without local interaction and build. 
      # - "com.centurylinklabs.watchtower.monitor-only=true"
      # Disabling watchtower on this container entirely instead
      - "com.centurylinklabs.watchtower.enable=false"

# secrets not yet built into wg-easy (Aug 2024)
# secrets:
#   wireguard_password_hash:
#     file: ${SECRETS}/wireguard/wireguard_password_hash