name: Docker Compose Validation
run-name: Testing that each docker-compose.yml file is valid
on:
  push:
    branches:
      - main
    paths:
    - '**/docker-compose.yml'
  pull_request:
    paths:
    - '**/docker-compose.yml'

jobs:
  docker-compose-validation:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      
      - name: Check Docker version
        run: docker --version

      - name: Find all compose files
        id: finding-files
        run: |
          {
            echo 'FILELIST<<EOF'
            find . -name 'docker-compose.yml' -print 
            echo EOF
          } >> $GITHUB_ENV

      # - name: Check each compose file's syntax, so that it will at least run
      #   run: |
      #     error=false
      #     for i in $FILELIST; do
      #       config_check=""
      #       echo -n "Checking $i ..."
      #       config_check="$(docker compose -f ${i} config -q 2>&1 || true)"
            
      #       if [ -z "$config_check" ]; then
      #         echo "OK"
      #       else
      #         echo "ERROR"
      #         echo "$config_check"
      #         error=true
      #       fi
      #     done

      #     if $error; then
      #       echo "One or more docker-compose.yml files have errors. Please fix them."
      #       exit 1
      #     fi
